<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="FastFoodForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FastFoodForm.Designer.cs">
      <DependentUpon>FastFoodForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="FastFoodForm.resx">
      <DependentUpon>FastFoodForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>